apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgresql

labels:
  - pairs:
      app: postgresql
    includeSelectors: true
    includeTemplates: true

resources:
  - namespace.yaml
  - service.yaml
  - statefulset.yaml

images:
  - name: postgres
    newTag: "18.2"
