name: Rendered Manifests

on:
  push:
    branches:
      - main
    paths:
      - "deployments/**"
      - "!deployments/**/install.yaml"

jobs:
  changes:
    outputs:
      ingress-nginx: ${{ steps.filter.outputs.ingress-nginx }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Detect changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        id: filter
        with:
          filters: |
            ingress-nginx:
              - 'deployments/ingress-nginx/**'

  ingress-nginx:
    needs: changes
    if: needs.changes.outputs.ingress-nginx == 'true'
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/reusable-rendered-manifests.yaml
    with:
      name: ingress-nginx
