name: Rendered Manifests

on:
  push:
    branches:
      - main
    paths:
      - "deployments/**"
      - "!deployments/**/install.yaml"

jobs:
  changes:
    outputs:
      ingress-nginx: ${{ steps.filter.outputs.ingress-nginx }}
      postgresql: ${{ steps.filter.outputs.postgresql }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Detect changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        id: filter
        with:
          filters: |
            ingress-nginx:
              - 'deployments/ingress-nginx/base/**'
            postgresql:
              - 'deployments/postgresql/base/**'

  ingress-nginx:
    needs: changes
    if: needs.changes.outputs.ingress-nginx == 'true'
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/reuse-rendered-manifests.yaml
    with:
      name: ingress-nginx

  postgresql:
    needs: changes
    if: needs.changes.outputs.postgresql == 'true'
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/reuse-rendered-manifests.yaml
    with:
      name: postgresql
